// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------------------- //
// LED_multiplexer_sm0 //
// ------------------- //

#define LED_multiplexer_sm0_wrap_target 0
#define LED_multiplexer_sm0_wrap 8

static const uint16_t LED_multiplexer_sm0_program_instructions[] = {
            //     .wrap_target
    0x80a0, //  0: pull   block                      
    0x6004, //  1: out    pins, 4                    
    0x7f30, //  2: out    x, 16                  [31]
    0x20c6, //  3: wait   1 irq, 6                   
    0xe003, //  4: set    pins, 3                    
    0xe000, //  5: set    pins, 0                    
    0xc007, //  6: irq    nowait 7                   
    0x0047, //  7: jmp    x--, 7                     
    0xe002, //  8: set    pins, 2                    
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program LED_multiplexer_sm0_program = {
    .instructions = LED_multiplexer_sm0_program_instructions,
    .length = 9,
    .origin = -1,
};

static inline pio_sm_config LED_multiplexer_sm0_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + LED_multiplexer_sm0_wrap_target, offset + LED_multiplexer_sm0_wrap);
    return c;
}
#endif

// ------------------- //
// LED_multiplexer_sm1 //
// ------------------- //

#define LED_multiplexer_sm1_wrap_target 0
#define LED_multiplexer_sm1_wrap 12

static const uint16_t LED_multiplexer_sm1_program_instructions[] = {
            //     .wrap_target
    0x80a0, //  0: pull   block                      
    0xa025, //  1: mov    x, status                  
    0x0024, //  2: jmp    !x, 4                      
    0xc000, //  3: irq    nowait 0                   
    0xe037, //  4: set    x, 23                      
    0xe000, //  5: set    pins, 0                    
    0x6001, //  6: out    pins, 1                    
    0xa042, //  7: nop                               
    0xe001, //  8: set    pins, 1                    
    0x0045, //  9: jmp    x--, 5                     
    0xe000, // 10: set    pins, 0                    
    0xc006, // 11: irq    nowait 6                   
    0x20c7, // 12: wait   1 irq, 7                   
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program LED_multiplexer_sm1_program = {
    .instructions = LED_multiplexer_sm1_program_instructions,
    .length = 13,
    .origin = -1,
};

static inline pio_sm_config LED_multiplexer_sm1_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + LED_multiplexer_sm1_wrap_target, offset + LED_multiplexer_sm1_wrap);
    return c;
}
#endif
